apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xconnectionv0alpha1s.oss.grafana.net.namespaced
  name: connectionv0alpha1-namespaced
spec:
  compositeTypeRef:
    apiVersion: oss.grafana.net.namespaced/v1alpha1
    kind: XConnectionV0Alpha1
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: oss.grafana.crossplane.io/v1alpha1
              kind: ConnectionV0Alpha1
            name: connectionv0alpha1
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.selectorLabel
                toFieldPath: "metadata.labels[\"selector\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.metadata.folderUid
                toFieldPath: spec.forProvider.metadata.folderUid
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.metadata.uid
                toFieldPath: spec.forProvider.metadata.uid
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.options.managerIdentity
                toFieldPath: spec.forProvider.options.managerIdentity
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.options.overwrite
                toFieldPath: spec.forProvider.options.overwrite
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.secure.privateKey
                toFieldPath: spec.forProvider.secure.privateKey
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.secure.token
                toFieldPath: spec.forProvider.secure.token
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.secureVersion
                toFieldPath: spec.forProvider.secureVersion
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.spec.description
                toFieldPath: spec.forProvider.spec.description
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.spec.github.appId
                toFieldPath: spec.forProvider.spec.github.appId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.spec.github.installationId
                toFieldPath: spec.forProvider.spec.github.installationId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.spec.title
                toFieldPath: spec.forProvider.spec.title
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.spec.type
                toFieldPath: spec.forProvider.spec.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.spec.url
                toFieldPath: spec.forProvider.spec.url
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.metadata.folderUid
                toFieldPath: spec.initProvider.metadata.folderUid
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.metadata.uid
                toFieldPath: spec.initProvider.metadata.uid
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.options.managerIdentity
                toFieldPath: spec.initProvider.options.managerIdentity
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.options.overwrite
                toFieldPath: spec.initProvider.options.overwrite
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.secure.privateKey
                toFieldPath: spec.initProvider.secure.privateKey
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.secure.token
                toFieldPath: spec.initProvider.secure.token
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.secureVersion
                toFieldPath: spec.initProvider.secureVersion
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.spec.description
                toFieldPath: spec.initProvider.spec.description
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.spec.github.appId
                toFieldPath: spec.initProvider.spec.github.appId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.spec.github.installationId
                toFieldPath: spec.initProvider.spec.github.installationId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.spec.title
                toFieldPath: spec.initProvider.spec.title
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.spec.type
                toFieldPath: spec.initProvider.spec.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.spec.url
                toFieldPath: spec.initProvider.spec.url
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform
    - functionRef:
        name: function-grafana-data
      step: grafana-data