apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xazurecredentials.cloudprovider.grafana.net.namespaced
  name: azurecredential-namespaced
spec:
  compositeTypeRef:
    apiVersion: cloudprovider.grafana.net.namespaced/v1alpha1
    kind: XAzureCredential
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: cloudprovider.grafana.crossplane.io/v1alpha1
              kind: AzureCredential
            name: azurecredential
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.clientId
                toFieldPath: spec.forProvider.clientId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.clientSecretSecretRef.key
                toFieldPath: spec.forProvider.clientSecretSecretRef.key
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.clientSecretSecretRef.name
                toFieldPath: spec.forProvider.clientSecretSecretRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.clientSecretSecretRef.namespace
                toFieldPath: spec.forProvider.clientSecretSecretRef.namespace
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.name
                toFieldPath: spec.forProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.resourceDiscoveryTagFilter
                toFieldPath: spec.forProvider.resourceDiscoveryTagFilter
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.stackId
                toFieldPath: spec.forProvider.stackId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.tenantId
                toFieldPath: spec.forProvider.tenantId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.clientId
                toFieldPath: spec.initProvider.clientId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.clientSecretSecretRef.key
                toFieldPath: spec.initProvider.clientSecretSecretRef.key
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.clientSecretSecretRef.name
                toFieldPath: spec.initProvider.clientSecretSecretRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.clientSecretSecretRef.namespace
                toFieldPath: spec.initProvider.clientSecretSecretRef.namespace
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.name
                toFieldPath: spec.initProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.resourceDiscoveryTagFilter
                toFieldPath: spec.initProvider.resourceDiscoveryTagFilter
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.stackId
                toFieldPath: spec.initProvider.stackId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.tenantId
                toFieldPath: spec.initProvider.tenantId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform