apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xserviceaccounttokens.oss.grafana.crossplane.io.namespaced
  name: serviceaccounttoken-namespaced
spec:
  compositeTypeRef:
    apiVersion: oss.grafana.crossplane.io.namespaced/v1alpha1
    kind: XServiceAccountToken
  resources:
    - base:
        apiVersion: oss.grafana.crossplane.io/v1alpha1
        kind: ServiceAccountToken
      name: serviceaccounttoken
      patches:
        - fromFieldPath: spec.parameters.externalName
          toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.name
          toFieldPath: spec.forProvider.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.secondsToLive
          toFieldPath: spec.forProvider.secondsToLive
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountId
          toFieldPath: spec.forProvider.serviceAccountId
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountRef.name
          toFieldPath: spec.forProvider.serviceAccountRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountRef.policy.resolution
          toFieldPath: spec.forProvider.serviceAccountRef.policy.resolution
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountRef.policy.resolve
          toFieldPath: spec.forProvider.serviceAccountRef.policy.resolve
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountSelector.matchControllerRef
          toFieldPath: spec.forProvider.serviceAccountSelector.matchControllerRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountSelector.matchLabels
          toFieldPath: spec.forProvider.serviceAccountSelector.matchLabels
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountSelector.policy.resolution
          toFieldPath: spec.forProvider.serviceAccountSelector.policy.resolution
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.forProvider.serviceAccountSelector.policy.resolve
          toFieldPath: spec.forProvider.serviceAccountSelector.policy.resolve
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.name
          toFieldPath: spec.initProvider.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.secondsToLive
          toFieldPath: spec.initProvider.secondsToLive
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountId
          toFieldPath: spec.initProvider.serviceAccountId
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountRef.name
          toFieldPath: spec.initProvider.serviceAccountRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountRef.policy.resolution
          toFieldPath: spec.initProvider.serviceAccountRef.policy.resolution
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountRef.policy.resolve
          toFieldPath: spec.initProvider.serviceAccountRef.policy.resolve
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountSelector.matchControllerRef
          toFieldPath: spec.initProvider.serviceAccountSelector.matchControllerRef
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountSelector.matchLabels
          toFieldPath: spec.initProvider.serviceAccountSelector.matchLabels
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountSelector.policy.resolution
          toFieldPath: spec.initProvider.serviceAccountSelector.policy.resolution
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.initProvider.serviceAccountSelector.policy.resolve
          toFieldPath: spec.initProvider.serviceAccountSelector.policy.resolve
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.managementPolicies
          toFieldPath: spec.managementPolicies
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.providerConfigRef.name
          toFieldPath: spec.providerConfigRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
          toFieldPath: spec.providerConfigRef.policy.resolution
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
          toFieldPath: spec.providerConfigRef.policy.resolve
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
          toFieldPath: spec.publishConnectionDetailsTo.configRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
          toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
          toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
          toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
          toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
          toFieldPath: spec.publishConnectionDetailsTo.metadata.type
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
          toFieldPath: spec.publishConnectionDetailsTo.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          type: FromCompositeFieldPath
        - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
          toFieldPath: spec.writeConnectionSecretToRef.namespace
          type: FromCompositeFieldPath