apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xalerts.ml.grafana.net.namespaced
  name: alert-namespaced
spec:
  compositeTypeRef:
    apiVersion: ml.grafana.net.namespaced/v1alpha1
    kind: XAlert
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: ml.grafana.crossplane.io/v1alpha1
              kind: Alert
            name: alert
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.selectorLabel
                toFieldPath: "metadata.labels[\"selector\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.annotations
                toFieldPath: spec.forProvider.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.anomalyCondition
                toFieldPath: spec.forProvider.anomalyCondition
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.for
                toFieldPath: spec.forProvider.for
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.jobId
                toFieldPath: spec.forProvider.jobId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.labels
                toFieldPath: spec.forProvider.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.noDataState
                toFieldPath: spec.forProvider.noDataState
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.outlierId
                toFieldPath: spec.forProvider.outlierId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.threshold
                toFieldPath: spec.forProvider.threshold
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.title
                toFieldPath: spec.forProvider.title
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.window
                toFieldPath: spec.forProvider.window
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.annotations
                toFieldPath: spec.initProvider.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.anomalyCondition
                toFieldPath: spec.initProvider.anomalyCondition
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.for
                toFieldPath: spec.initProvider.for
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.jobId
                toFieldPath: spec.initProvider.jobId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.labels
                toFieldPath: spec.initProvider.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.noDataState
                toFieldPath: spec.initProvider.noDataState
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.outlierId
                toFieldPath: spec.initProvider.outlierId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.threshold
                toFieldPath: spec.initProvider.threshold
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.title
                toFieldPath: spec.initProvider.title
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.window
                toFieldPath: spec.initProvider.window
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform