apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xnotificationpolicies.alerting.grafana.net.namespaced
  name: notificationpolicy-namespaced
spec:
  compositeTypeRef:
    apiVersion: alerting.grafana.net.namespaced/v1alpha1
    kind: XNotificationPolicy
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: alerting.grafana.crossplane.io/v1alpha1
              kind: NotificationPolicy
            name: notificationpolicy
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPoint
                toFieldPath: spec.forProvider.contactPoint
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPointRef.name
                toFieldPath: spec.forProvider.contactPointRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPointRef.policy.resolution
                toFieldPath: spec.forProvider.contactPointRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPointRef.policy.resolve
                toFieldPath: spec.forProvider.contactPointRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPointSelector.matchControllerRef
                toFieldPath: spec.forProvider.contactPointSelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPointSelector.matchLabels
                toFieldPath: spec.forProvider.contactPointSelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPointSelector.policy.resolution
                toFieldPath: spec.forProvider.contactPointSelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.contactPointSelector.policy.resolve
                toFieldPath: spec.forProvider.contactPointSelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.disableProvenance
                toFieldPath: spec.forProvider.disableProvenance
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.groupBy
                toFieldPath: spec.forProvider.groupBy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.groupInterval
                toFieldPath: spec.forProvider.groupInterval
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.groupWait
                toFieldPath: spec.forProvider.groupWait
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.orgId
                toFieldPath: spec.forProvider.orgId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.organizationRef.name
                toFieldPath: spec.forProvider.organizationRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.organizationRef.policy.resolution
                toFieldPath: spec.forProvider.organizationRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.organizationRef.policy.resolve
                toFieldPath: spec.forProvider.organizationRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.organizationSelector.matchControllerRef
                toFieldPath: spec.forProvider.organizationSelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.organizationSelector.matchLabels
                toFieldPath: spec.forProvider.organizationSelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.organizationSelector.policy.resolution
                toFieldPath: spec.forProvider.organizationSelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.organizationSelector.policy.resolve
                toFieldPath: spec.forProvider.organizationSelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.policy
                toFieldPath: spec.forProvider.policy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.repeatInterval
                toFieldPath: spec.forProvider.repeatInterval
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPoint
                toFieldPath: spec.initProvider.contactPoint
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPointRef.name
                toFieldPath: spec.initProvider.contactPointRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPointRef.policy.resolution
                toFieldPath: spec.initProvider.contactPointRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPointRef.policy.resolve
                toFieldPath: spec.initProvider.contactPointRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPointSelector.matchControllerRef
                toFieldPath: spec.initProvider.contactPointSelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPointSelector.matchLabels
                toFieldPath: spec.initProvider.contactPointSelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPointSelector.policy.resolution
                toFieldPath: spec.initProvider.contactPointSelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.contactPointSelector.policy.resolve
                toFieldPath: spec.initProvider.contactPointSelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.disableProvenance
                toFieldPath: spec.initProvider.disableProvenance
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.groupBy
                toFieldPath: spec.initProvider.groupBy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.groupInterval
                toFieldPath: spec.initProvider.groupInterval
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.groupWait
                toFieldPath: spec.initProvider.groupWait
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.orgId
                toFieldPath: spec.initProvider.orgId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.organizationRef.name
                toFieldPath: spec.initProvider.organizationRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.organizationRef.policy.resolution
                toFieldPath: spec.initProvider.organizationRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.organizationRef.policy.resolve
                toFieldPath: spec.initProvider.organizationRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.organizationSelector.matchControllerRef
                toFieldPath: spec.initProvider.organizationSelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.organizationSelector.matchLabels
                toFieldPath: spec.initProvider.organizationSelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.organizationSelector.policy.resolution
                toFieldPath: spec.initProvider.organizationSelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.organizationSelector.policy.resolve
                toFieldPath: spec.initProvider.organizationSelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.policy
                toFieldPath: spec.initProvider.policy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.repeatInterval
                toFieldPath: spec.initProvider.repeatInterval
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform