apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  name: xaccesspolicyrotatingtokens.cloud.grafana.net.namespaced
spec:
  claimNames:
    kind: AccessPolicyRotatingToken
    plural: accesspolicyrotatingtokens
  defaultCompositionRef:
    name: accesspolicyrotatingtoken-namespaced
  group: cloud.grafana.net.namespaced
  names:
    kind: XAccessPolicyRotatingToken
    plural: xaccesspolicyrotatingtokens
  versions:
    - name: v1alpha1
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                parameters:
                  description: AccessPolicyRotatingTokenSpec defines the desired state of AccessPolicyRotatingToken
                  properties:
                    deletionPolicy:
                      default: Delete
                      description: |-
                        DeletionPolicy specifies what will happen to the underlying external
                        when this managed resource is deleted - either "Delete" or "Orphan" the
                        external resource.
                        This field is planned to be deprecated in favor of the ManagementPolicies
                        field in a future release. Currently, both could be set independently and
                        non-default values would be honored if the feature flag is enabled.
                        See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                      enum:
                        - Orphan
                        - Delete
                      type: string
                    externalName:
                      description: |
                        The name of the managed resource inside the Provider.
                        By default Providers give external resources the same name as the Kubernetes object. A provider uses the external name to lookup a managed resource in an external system. The provider looks up the resource in the external system to determine if it exists, and if it matches the managed resource’s desired state. If the provider can’t find the resource, it creates it.
                        
                        Docs: https://docs.crossplane.io/latest/concepts/managed-resources/#naming-external-resources
                      type: string
                    forProvider:
                      properties:
                        accessPolicyId:
                          description: |-
                            (String) ID of the access policy for which to create a token.
                            ID of the access policy for which to create a token.
                          type: string
                        deleteOnDestroy:
                          description: "Use it with lifecycle { create_before_destroy = true } to make sure that the new token is created before the old one is deleted. Defaults to false. Use it with `lifecycle { create_before_destroy = true }` to make sure that the new token is created before the old one is deleted. Defaults to `false`."
                          type: boolean
                        displayName:
                          description: |-
                            (String) Display name of the access policy token. Defaults to the name.
                            Display name of the access policy token. Defaults to the name.
                          type: string
                        earlyRotationWindow:
                          description: |-
                            (String) Duration of the window before expiring where the token can be rotated (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                            Duration of the window before expiring where the token can be rotated (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                          type: string
                        expireAfter:
                          description: |-
                            (String) Duration after which the token will expire (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                            Duration after which the token will expire (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                          type: string
                        namePrefix:
                          description: |-
                            <expiration_timestamp>'
                            Prefix for the name of the access policy token. The actual name will be stored in the computed field `name`, which will be in the format '<name_prefix>-<expiration_timestamp>'
                          type: string
                        region:
                          description: |-
                            cloud/developer-resources/api-reference/cloud-api/#list-regions.
                            Region of the access policy. Should be set to the same region as the access policy. Use the region list API to get the list of available regions: https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-regions.
                          type: string
                      type: object
                    initProvider:
                      description: |-
                        THIS IS A BETA FIELD. It will be honored
                        unless the Management Policies feature flag is disabled.
                        InitProvider holds the same fields as ForProvider, with the exception
                        of Identifier and other resource reference fields. The fields that are
                        in InitProvider are merged into ForProvider when the resource is created.
                        The same fields are also added to the terraform ignore_changes hook, to
                        avoid updating them after creation. This is useful for fields that are
                        required on creation, but we do not desire to update them after creation,
                        for example because of an external controller is managing them, like an
                        autoscaler.
                      properties:
                        accessPolicyId:
                          description: |-
                            (String) ID of the access policy for which to create a token.
                            ID of the access policy for which to create a token.
                          type: string
                        deleteOnDestroy:
                          description: "Use it with lifecycle { create_before_destroy = true } to make sure that the new token is created before the old one is deleted. Defaults to false. Use it with `lifecycle { create_before_destroy = true }` to make sure that the new token is created before the old one is deleted. Defaults to `false`."
                          type: boolean
                        displayName:
                          description: |-
                            (String) Display name of the access policy token. Defaults to the name.
                            Display name of the access policy token. Defaults to the name.
                          type: string
                        earlyRotationWindow:
                          description: |-
                            (String) Duration of the window before expiring where the token can be rotated (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                            Duration of the window before expiring where the token can be rotated (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                          type: string
                        expireAfter:
                          description: |-
                            (String) Duration after which the token will expire (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                            Duration after which the token will expire (e.g. '24h', '30m', '1h30m'). Valid units are 's' (seconds), 'm' (minutes) and 'h' (hours).
                          type: string
                        namePrefix:
                          description: |-
                            <expiration_timestamp>'
                            Prefix for the name of the access policy token. The actual name will be stored in the computed field `name`, which will be in the format '<name_prefix>-<expiration_timestamp>'
                          type: string
                        region:
                          description: |-
                            cloud/developer-resources/api-reference/cloud-api/#list-regions.
                            Region of the access policy. Should be set to the same region as the access policy. Use the region list API to get the list of available regions: https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/cloud-api/#list-regions.
                          type: string
                      type: object
                    managementPolicies:
                      default:
                        - "*"
                      description: |-
                        THIS IS A BETA FIELD. It is on by default but can be opted out
                        through a Crossplane feature flag.
                        ManagementPolicies specify the array of actions Crossplane is allowed to
                        take on the managed and external resources.
                        This field is planned to replace the DeletionPolicy field in a future
                        release. Currently, both could be set independently and non-default
                        values would be honored if the feature flag is enabled. If both are
                        custom, the DeletionPolicy field will be ignored.
                        See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
                        and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
                      items:
                        description: |-
                          A ManagementAction represents an action that the Crossplane controllers
                          can take on an external resource.
                        enum:
                          - Observe
                          - Create
                          - Update
                          - Delete
                          - LateInitialize
                          - "*"
                        type: string
                      type: array
                    providerConfigRef:
                      default:
                        name: default
                      description: |-
                        ProviderConfigReference specifies how the provider that will be used to
                        create, observe, update, and delete this managed resource should be
                        configured.
                      properties:
                        name:
                          description: Name of the referenced object.
                          type: string
                        policy:
                          description: Policies for referencing.
                          properties:
                            resolution:
                              default: Required
                              description: |-
                                Resolution specifies whether resolution of this reference is required.
                                The default is 'Required', which means the reconcile will fail if the
                                reference cannot be resolved. 'Optional' means this reference will be
                                a no-op if it cannot be resolved.
                              enum:
                                - Required
                                - Optional
                              type: string
                            resolve:
                              description: |-
                                Resolve specifies when this reference should be resolved. The default
                                is 'IfNotPresent', which will attempt to resolve the reference only when
                                the corresponding field is not present. Use 'Always' to resolve the
                                reference on every reconcile.
                              enum:
                                - Always
                                - IfNotPresent
                              type: string
                          type: object
                      required:
                        - name
                      type: object
                    selectorLabel:
                      description: Configure a custom label for use with selector.matchLabels.
                      type: string
                    writeConnectionSecretToRef:
                      description: |-
                        WriteConnectionSecretToReference specifies the namespace and name of a
                        Secret to which any connection details for this managed resource should
                        be written. Connection details frequently include the endpoint, username,
                        and password required to connect to the managed resource.
                      properties:
                        name:
                          description: Name of the secret.
                          type: string
                        namespace:
                          description: Namespace of the secret.
                          type: string
                      required:
                        - name
                        - namespace
                      type: object
                  required:
                    - forProvider
                  type: object
                  x-kubernetes-validations:
                    - message: spec.forProvider.accessPolicyId is a required parameter
                      rule: "!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accessPolicyId) || (has(self.initProvider) && has(self.initProvider.accessPolicyId))"
                    - message: spec.forProvider.earlyRotationWindow is a required parameter
                      rule: "!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.earlyRotationWindow) || (has(self.initProvider) && has(self.initProvider.earlyRotationWindow))"
                    - message: spec.forProvider.expireAfter is a required parameter
                      rule: "!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expireAfter) || (has(self.initProvider) && has(self.initProvider.expireAfter))"
                    - message: spec.forProvider.namePrefix is a required parameter
                      rule: "!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.namePrefix) || (has(self.initProvider) && has(self.initProvider.namePrefix))"
                    - message: spec.forProvider.region is a required parameter
                      rule: "!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))"
              type: object
          type: object
      served: true