apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xslos.slo.grafana.net.namespaced
  name: slo-namespaced
spec:
  compositeTypeRef:
    apiVersion: slo.grafana.net.namespaced/v1alpha1
    kind: XSLO
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: slo.grafana.crossplane.io/v1alpha1
              kind: SLO
            name: slo
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.alerting
                toFieldPath: spec.forProvider.alerting
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.description
                toFieldPath: spec.forProvider.description
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.destinationDatasource
                toFieldPath: spec.forProvider.destinationDatasource
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.folderUid
                toFieldPath: spec.forProvider.folderUid
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.label
                toFieldPath: spec.forProvider.label
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.name
                toFieldPath: spec.forProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.objectives
                toFieldPath: spec.forProvider.objectives
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.query
                toFieldPath: spec.forProvider.query
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.searchExpression
                toFieldPath: spec.forProvider.searchExpression
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.alerting
                toFieldPath: spec.initProvider.alerting
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.description
                toFieldPath: spec.initProvider.description
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.destinationDatasource
                toFieldPath: spec.initProvider.destinationDatasource
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.folderUid
                toFieldPath: spec.initProvider.folderUid
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.label
                toFieldPath: spec.initProvider.label
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.name
                toFieldPath: spec.initProvider.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.objectives
                toFieldPath: spec.initProvider.objectives
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.query
                toFieldPath: spec.initProvider.query
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.searchExpression
                toFieldPath: spec.initProvider.searchExpression
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform