apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xchecks.sm.grafana.net.namespaced
  name: check-namespaced
spec:
  compositeTypeRef:
    apiVersion: sm.grafana.net.namespaced/v1alpha1
    kind: XCheck
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: sm.grafana.crossplane.io/v1alpha1
              kind: Check
            name: check
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.alertSensitivity
                toFieldPath: spec.forProvider.alertSensitivity
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.basicMetricsOnly
                toFieldPath: spec.forProvider.basicMetricsOnly
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.enabled
                toFieldPath: spec.forProvider.enabled
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.frequency
                toFieldPath: spec.forProvider.frequency
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.job
                toFieldPath: spec.forProvider.job
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.labels
                toFieldPath: spec.forProvider.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.probes
                toFieldPath: spec.forProvider.probes
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.settings
                toFieldPath: spec.forProvider.settings
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.target
                toFieldPath: spec.forProvider.target
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.timeout
                toFieldPath: spec.forProvider.timeout
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.alertSensitivity
                toFieldPath: spec.initProvider.alertSensitivity
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.basicMetricsOnly
                toFieldPath: spec.initProvider.basicMetricsOnly
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.enabled
                toFieldPath: spec.initProvider.enabled
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.frequency
                toFieldPath: spec.initProvider.frequency
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.job
                toFieldPath: spec.initProvider.job
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.labels
                toFieldPath: spec.initProvider.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.probes
                toFieldPath: spec.initProvider.probes
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.settings
                toFieldPath: spec.initProvider.settings
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.target
                toFieldPath: spec.initProvider.target
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.timeout
                toFieldPath: spec.initProvider.timeout
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.name
                toFieldPath: spec.publishConnectionDetailsTo.configRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolution
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.configRef.policy.resolve
                toFieldPath: spec.publishConnectionDetailsTo.configRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.annotations
                toFieldPath: spec.publishConnectionDetailsTo.metadata.annotations
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.labels
                toFieldPath: spec.publishConnectionDetailsTo.metadata.labels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.metadata.type
                toFieldPath: spec.publishConnectionDetailsTo.metadata.type
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.publishConnectionDetailsTo.name
                toFieldPath: spec.publishConnectionDetailsTo.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform