apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  annotations:
    tanka.dev/namespaced: "false"
  labels:
    crossplane.io/xrd: xcheckalerts.sm.grafana.net.namespaced
  name: checkalerts-namespaced
spec:
  compositeTypeRef:
    apiVersion: sm.grafana.net.namespaced/v1alpha1
    kind: XCheckAlerts
  mode: Pipeline
  pipeline:
    - functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - base:
              apiVersion: sm.grafana.crossplane.io/v1alpha1
              kind: CheckAlerts
            name: checkalerts
            patches:
              - fromFieldPath: spec.parameters.externalName
                toFieldPath: "metadata.annotations[\"crossplane.io/external-name\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.selectorLabel
                toFieldPath: "metadata.labels[\"selector\"]"
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.alerts
                toFieldPath: spec.forProvider.alerts
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkId
                toFieldPath: spec.forProvider.checkId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkRef.name
                toFieldPath: spec.forProvider.checkRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkRef.policy.resolution
                toFieldPath: spec.forProvider.checkRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkRef.policy.resolve
                toFieldPath: spec.forProvider.checkRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkSelector.matchControllerRef
                toFieldPath: spec.forProvider.checkSelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkSelector.matchLabels
                toFieldPath: spec.forProvider.checkSelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkSelector.policy.resolution
                toFieldPath: spec.forProvider.checkSelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.forProvider.checkSelector.policy.resolve
                toFieldPath: spec.forProvider.checkSelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.alerts
                toFieldPath: spec.initProvider.alerts
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkId
                toFieldPath: spec.initProvider.checkId
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkRef.name
                toFieldPath: spec.initProvider.checkRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkRef.policy.resolution
                toFieldPath: spec.initProvider.checkRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkRef.policy.resolve
                toFieldPath: spec.initProvider.checkRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkSelector.matchControllerRef
                toFieldPath: spec.initProvider.checkSelector.matchControllerRef
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkSelector.matchLabels
                toFieldPath: spec.initProvider.checkSelector.matchLabels
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkSelector.policy.resolution
                toFieldPath: spec.initProvider.checkSelector.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.initProvider.checkSelector.policy.resolve
                toFieldPath: spec.initProvider.checkSelector.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.managementPolicies
                toFieldPath: spec.managementPolicies
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.name
                toFieldPath: spec.providerConfigRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolution
                toFieldPath: spec.providerConfigRef.policy.resolution
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.providerConfigRef.policy.resolve
                toFieldPath: spec.providerConfigRef.policy.resolve
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.name
                toFieldPath: spec.writeConnectionSecretToRef.name
                type: FromCompositeFieldPath
              - fromFieldPath: spec.parameters.writeConnectionSecretToRef.namespace
                toFieldPath: spec.writeConnectionSecretToRef.namespace
                type: FromCompositeFieldPath
      step: patch-and-transform
    - functionRef:
        name: function-grafana-data
      step: grafana-data